
pull_request_rules:

  # implementing PR delay logic: apply a label after 2 days of inactivity
  # the label will allow Mergify to merge (see #8442, #8448)
  - actions:
      label:
        add:
          - merge delay passed
    name: Wait for 2 days before validating merge
    conditions:
      - updated-at<2 days ago
      - or:
          - label=merge me
          - label=squash+merge me
          - label=merge+no rebase
      - '#approved-reviews-by>=2'

  # rebase+merge strategy
  - actions:
      merge:
        method: merge
    name: Merge "merge+no rebase" pull requests directly (without a queue)
    conditions:
      - base=master
      - label=merge+no rebase
      - label=merge delay passed
      - '#approved-reviews-by>=2'

  # rebase+merge strategy for backports: require 1 approver instead of 2
  - actions:
      label:
        add:
          - backport
    name: Label backports as such
    conditions:
      - body~=automatic backport

  - name: Put backports in the rebase+merge queue + Put pull requests in the rebase+merge
      queue + Put pull requests in the squash+merge queue
    conditions: []
    actions:
      queue:
queue_rules:
  - name: duplicated default from Put pull requests in the rebase+merge queue
    queue_conditions:
      - base=master
      - label=merge me
      - label=merge delay passed
      - '#approved-reviews-by>=2'
    merge_conditions: []
    update_bot_account: Mikolaj
    update_method: rebase
    merge_method: merge
  - name: duplicated default from Put pull requests in the squash+merge queue
    queue_conditions:
      - base=master
      - label=squash+merge me
      - label=merge delay passed
      - '#approved-reviews-by>=2'
    merge_conditions: []
    update_bot_account: Mikolaj
    update_method: merge
    merge_method: squash
  - name: duplicated default from Put backports in the rebase+merge queue
    queue_conditions:
      - label=merge me
      - base!=master
      - body~=backport
      - '#approved-reviews-by>=1'
    merge_conditions: []
    update_bot_account: Mikolaj
    update_method: rebase
    merge_method: merge
  - name: default
    update_bot_account: Mikolaj
